services:
  question-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: question-service
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_credentials.json
      PORT: 3001
    secrets:
      - gcp_credentials.json
    ports:
      - 3001:3001
    networks:
      - demo-network
    
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_credentials.json
      PORT: 3002
    secrets:
      - gcp_credentials.json
    ports:
      - 3002:3002
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

secrets:
  gcp_credentials.json:
    file: ./.firebase/service-account.json
    